Documentação do Pytorch:

https://pytorch.org/docs/stable/tensors.html



In [ ]:
# Tensor A partir de listas

import torch


ll = [[1, 2, 3], [4, 5, 6]]

ll = [[1, 2, 3], [4, 5, 6]]
tns = torch.Tensor(ll)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(ll)
print(tns.dtype)
print(tns)

tns = torch.LongTensor(ll)
print(tns.dtype)
print(tns)


torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# A partir do numpy

import torch
import numpy as np

arrfloat = np.random.rand(3,4)
arrint = (arrfloat*10).astype(int)

tsnfloat = torch.from_numpy(arrfloat)
tsnint = torch.from_numpy(arrint)

print(arrfloat)
print(arrint)
print(tsnfloat)
print(tsnint)



[[0.93399492 0.24877572 0.13657301 0.076697  ]
 [0.44434828 0.53567984 0.96183158 0.96464339]
 [0.26682407 0.85693849 0.38047134 0.43293388]]
[[9 2 1 0]
 [4 5 9 9]
 [2 8 3 4]]
tensor([[0.9340, 0.2488, 0.1366, 0.0767],
        [0.4443, 0.5357, 0.9618, 0.9646],
        [0.2668, 0.8569, 0.3805, 0.4329]], dtype=torch.float64)
tensor([[9, 2, 1, 0],
        [4, 5, 9, 9],
        [2, 8, 3, 4]])


In [ ]:
# Inicializando Tensores

import torch
import numpy as np

tsn1 = torch.ones(2, 3)
tsn0 = torch.zeros(4, 5)
tsnr = torch.randn(3, 3)

print(tsn1)
print(tsn0)
print(tsnr)




tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.5265, -0.1706, -2.7293],
        [-0.2218, -0.2445,  0.8138],
        [ 0.0200,  1.7076, -1.0850]])


In [ ]:
# Inicializando Tensores

import torch
import numpy as np


tsnr = torch.randn(3, 3)
arr = tsnr.data.numpy()
print(arr)


[[-0.6430746   0.7495865   0.01156517]
 [ 1.2668123   0.54776806 -1.3408281 ]
 [-0.26828724  1.089448   -1.0117223 ]]


In [ ]:
tsnr = torch.randn(3, 3)
arr = tsnr.data.numpy()
print(tsnr)
tsnr[0, 2] = -10
print(tsnr)
print(tsnr[0:2, 1:3])


tensor([[-0.2182, -1.0513,  0.5444],
        [-0.4574,  0.1255, -0.5275],
        [-0.8435, -0.1035,  0.4510]])
tensor([[ -0.2182,  -1.0513, -10.0000],
        [ -0.4574,   0.1255,  -0.5275],
        [ -0.8435,  -0.1035,   0.4510]])
tensor([[ -1.0513, -10.0000],
        [  0.1255,  -0.5275]])


In [ ]:
tsnr1 = torch.ones(3, 3)
tsnr2 = torch.ones(3, 3)
tsn_pp = tsnr1*tsnr2
tsn_mul = torch.mm(tsnr1, tsnr1.T)
print(tsn_pp)
print(tsn_mul)



tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


In [ ]:
# tsnr1 = torch.ones(2, 2, 3)
tsnr1 = torch.rand(2, 2, 3)

print("--")
print(tsnr1.shape)
print("--")
print(tsnr1.size())

tsnr1_view = tsnr1.view(12)
print("--")
print(tsnr1_view)
print("--")
print(tsnr1)

--
torch.Size([2, 2, 3])
--
torch.Size([2, 2, 3])
--
tensor([0.7980, 0.4370, 0.2767, 0.0651, 0.3759, 0.5079, 0.9869, 0.3375, 0.6295,
        0.0893, 0.8400, 0.8378])
--
tensor([[[0.7980, 0.4370, 0.2767],
         [0.0651, 0.3759, 0.5079]],

        [[0.9869, 0.3375, 0.6295],
         [0.0893, 0.8400, 0.8378]]])


In [ ]:
import torch

tsnr1 = torch.rand(2, 2, 3)
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)

tsnr1.to(device)
print(tsnr1)

cuda
tensor([[[0.2870, 0.1502, 0.0088],
         [0.5522, 0.6573, 0.4211]],

        [[0.9716, 0.3321, 0.5544],
         [0.2133, 0.0109, 0.5213]]])


In [ ]:
import torch
tns = torch.randn(9, 12)
tns1 = tns[0:5, 0:4]
tns2 = tns[5:, 4:]

resultado = torch.mm(tns1, tns2)
print(resultado.size())

torch.Size([5, 8])


In [ ]:
## Resumo do código
import torch 
tns1 = torch.randn(7,7,3)
tns2 = torch.randn(147, 1)

tns1 = tns1.view(-1, 1)
print(tns1)
soma = tns1 + tns2
print(soma)

tensor([[-4.8376e-01],
        [ 1.3552e+00],
        [-1.0721e+00],
        [ 4.4539e-01],
        [-5.8265e-01],
        [ 9.5708e-01],
        [ 2.9676e-01],
        [-4.4025e-01],
        [-1.8486e+00],
        [-6.2187e-02],
        [-5.0665e-01],
        [-1.5635e+00],
        [ 9.6191e-02],
        [ 5.0241e-01],
        [ 2.4854e-01],
        [ 8.5801e-01],
        [ 3.4239e-01],
        [ 1.9586e-01],
        [ 1.4805e+00],
        [ 6.2527e-01],
        [ 8.6385e-01],
        [ 4.7069e-01],
        [ 3.0099e-01],
        [-5.9352e-01],
        [ 1.4605e+00],
        [ 2.3425e-01],
        [-5.8681e-01],
        [-8.1183e-01],
        [ 2.1745e+00],
        [ 7.0204e-01],
        [ 1.0674e+00],
        [-7.4801e-01],
        [-8.0537e-01],
        [ 8.1841e-02],
        [ 7.8593e-01],
        [ 3.4164e-01],
        [-1.4699e+00],
        [-1.5974e-01],
        [-5.9565e-01],
        [-1.4934e+00],
        [ 3.0697e-01],
        [-2.9316e-01],
        [ 5.9492e-01],
        [-3